import { CompanyStyle, Difficulty, QuestionType, TargetLevel } from "@prisma/client";

type Example = {
  input: string;
  output: string;
  explanation?: string;
};

export type QuestionBankEntry = {
  type: QuestionType;
  title: string;
  slug: string;
  prompt: string;
  difficulty: Difficulty;
  companyStyle: CompanyStyle;
  levelTarget?: TargetLevel | null;
  estimatedMinutes: number;
  topicTags: string[];
};

function buildCodingPrompt(description: string, examples: Example[], constraints: string[], notes?: string[]) {
  const exampleBlock = examples
    .map((example, index) => {
      const explanationLine = example.explanation ? `Explanation: ${example.explanation}\n` : "";
      return `Example ${index + 1}:\nInput: ${example.input}\nOutput: ${example.output}\n${explanationLine}`.trim();
    })
    .join("\n\n");

  const constraintsBlock = constraints.map((constraint) => `- ${constraint}`).join("\n");
  const notesBlock = notes && notes.length > 0 ? `\n\nNotes:\n${notes.map((note) => `- ${note}`).join("\n")}` : "";

  return `${description}\n\n${exampleBlock}\n\nConstraints:\n${constraintsBlock}${notesBlock}`;
}

const GENERIC = CompanyStyle.GENERIC;
const AMAZON = CompanyStyle.AMAZON;
const META = CompanyStyle.META;
const GOOGLE = CompanyStyle.GOOGLE;
const STRIPE = CompanyStyle.STRIPE;

const COMPANY_VARIANT_STYLES = [AMAZON, META, GOOGLE, STRIPE] as const;

function companyLabel(companyStyle: CompanyStyle) {
  switch (companyStyle) {
    case CompanyStyle.AMAZON:
      return "Amazon";
    case CompanyStyle.META:
      return "Meta";
    case CompanyStyle.GOOGLE:
      return "Google";
    case CompanyStyle.STRIPE:
      return "Stripe";
    case CompanyStyle.GENERIC:
    default:
      return "Generic";
  }
}

function buildCompanyVariant(entry: QuestionBankEntry, companyStyle: CompanyStyle): QuestionBankEntry {
  const label = companyLabel(companyStyle);
  return {
    ...entry,
    slug: `${entry.slug}-${companyStyle.toLowerCase()}`,
    companyStyle,
    topicTags: Array.from(new Set([...(entry.topicTags ?? []), `company:${companyStyle.toLowerCase()}`, `${label.toLowerCase()}-high-frequency`])),
  };
}

const BASE_QUESTION_BANK: QuestionBankEntry[] = [
  {
    type: QuestionType.CODING,
    title: "Two Sum",
    slug: "two-sum",
    prompt: buildCodingPrompt(
      "Given an integer array nums and an integer target, return the indices of two distinct values whose sum is exactly target.",
      [
        { input: "nums = [2, 7, 11, 15], target = 9", output: "[0, 1]" },
        { input: "nums = [3, 2, 4], target = 6", output: "[1, 2]" },
        { input: "nums = [3, 3], target = 6", output: "[0, 1]" },
      ],
      [
        "2 <= nums.length <= 10^4",
        "-10^9 <= nums[i] <= 10^9",
        "-10^9 <= target <= 10^9",
        "Exactly one valid answer exists",
      ],
      ["The same element cannot be used twice.", "You may return the answer in any order."],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["array", "hash-map"],
  },
  {
    type: QuestionType.CODING,
    title: "Merge Intervals",
    slug: "merge-intervals",
    prompt: buildCodingPrompt(
      "Given a list of closed intervals, merge every overlapping interval and return a list of non-overlapping intervals that covers the same ranges.",
      [
        { input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]" },
        { input: "intervals = [[1,4],[4,5]]", output: "[[1,5]]", explanation: "Touching endpoints still merge into one interval." },
      ],
      [
        "1 <= intervals.length <= 10^4",
        "intervals[i].length == 2",
        "0 <= start_i <= end_i <= 10^4",
      ],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 35,
    topicTags: ["intervals", "sorting"],
  },
  {
    type: QuestionType.CODING,
    title: "Top K Frequent Elements",
    slug: "top-k-frequent-elements",
    prompt: buildCodingPrompt(
      "Given an integer array nums and an integer k, return the k values that appear most often in the array.",
      [
        { input: "nums = [1,1,1,2,2,3], k = 2", output: "[1,2]" },
        { input: "nums = [1], k = 1", output: "[1]" },
        { input: "nums = [4,4,4,6,6,7,7,7,7], k = 2", output: "[7,4]" },
      ],
      [
        "1 <= nums.length <= 10^5",
        "-10^4 <= nums[i] <= 10^4",
        "1 <= k <= number of distinct values in nums",
        "The answer is unique",
      ],
      ["The result can be returned in any order."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["array", "hash-map", "heap", "bucket-sort"],
  },
  {
    type: QuestionType.CODING,
    title: "Design URL Shortener",
    slug: "design-url-shortener",
    prompt: buildCodingPrompt(
      "Implement a URL shortener service with two operations: encode(longUrl) should return a short string key, and decode(shortUrl) should recover the original long URL. Your design should use deterministic in-memory data structures for the interview version of the problem.",
      [
        {
          input: 'operations = [encode("https://example.com/a"), decode("short-1")]',
          output: '["short-1", "https://example.com/a"]',
        },
        {
          input: 'encode("https://example.com/a") twice',
          output: "The same long URL may map to the same short key if your implementation is deterministic",
        },
      ],
      [
        "1 <= number of operations <= 2 * 10^4",
        "1 <= URL length <= 2048",
        "All encode and decode operations must run in O(1) average time",
      ],
      [
        "You do not need to discuss distributed storage or internet-scale deployment in this coding version.",
        "Focus on the data structures and correctness of the encode/decode mapping.",
      ],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["design", "hash-map", "string"],
  },
  {
    type: QuestionType.SYSTEM_DESIGN,
    title: "Design Dropbox",
    slug: "system-design-dropbox",
    prompt: [
      "Design a Dropbox-like file storage and synchronization system.",
      "",
      "Scope:",
      "- Users can upload/download files across devices.",
      "- Files automatically sync after local changes.",
      "- Users can share links to files/folders.",
      "",
      "What to cover in the interview:",
      "- Functional requirements and non-functional goals (availability, durability, latency).",
      "- Core APIs (upload, download, metadata fetch, sync updates, share link).",
      "- High-level architecture and data flow.",
      "- Storage choices for metadata vs blob/object content.",
      "- Sync model, conflict handling, and consistency decisions.",
      "- Capacity estimates (traffic/storage growth) when scaling concerns are discussed.",
      "- Reliability risks (SPOF) and bottlenecks with mitigation.",
    ].join("\n"),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: null,
    estimatedMinutes: 50,
    topicTags: ["system-design", "storage", "sync", "distributed-systems", "api-design"],
  },
  {
    type: QuestionType.SYSTEM_DESIGN,
    title: "Design Gopuff Local Delivery Service",
    slug: "system-design-gopuff-local-delivery",
    prompt: [
      "Design a Gopuff-style local delivery platform backed by micro-fulfillment centers.",
      "",
      "Scope:",
      "- Users browse nearby inventory and place orders.",
      "- System routes order to a local warehouse and dispatches a courier.",
      "- Users can track order status in near real time.",
      "",
      "What to cover in the interview:",
      "- Functional requirements and non-functional goals (freshness, latency, reliability, cost).",
      "- Core APIs (catalog query, inventory check, order create, order status tracking).",
      "- High-level architecture and data flow across catalog, inventory, checkout, dispatch, tracking.",
      "- Inventory consistency and anti-oversell strategy.",
      "- Multi-warehouse routing and fallback behavior.",
      "- Capacity estimates once scaling/throughput concerns are in scope.",
      "- SPOF and bottleneck analysis plus mitigations.",
    ].join("\n"),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: null,
    estimatedMinutes: 50,
    topicTags: ["system-design", "local-delivery", "inventory", "consistency", "api-design"],
  },
  {
    type: QuestionType.CODING,
    title: "Valid Parentheses",
    slug: "valid-parentheses",
    prompt: buildCodingPrompt(
      "Given a string consisting only of bracket characters, determine whether the brackets form a valid sequence.",
      [
        { input: 's = "()"', output: "true" },
        { input: 's = "()[]{}"', output: "true" },
        { input: 's = "(]"', output: "false" },
      ],
      ["1 <= s.length <= 10^4", "s contains only bracket characters"],
      ["A sequence is valid when every opening bracket is closed by the same type in the correct order."],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["stack", "string"],
  },
  {
    type: QuestionType.CODING,
    title: "Best Time to Buy and Sell Stock",
    slug: "best-time-to-buy-and-sell-stock",
    prompt: buildCodingPrompt(
      "Given an array prices where prices[i] is the price of a stock on day i, return the maximum profit from one buy followed by one sell.",
      [
        { input: "prices = [7,1,5,3,6,4]", output: "5" },
        { input: "prices = [7,6,4,3,1]", output: "0" },
      ],
      ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
      ["You must buy before you sell.", "If no profit is possible, return 0."],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["array", "greedy"],
  },
  {
    type: QuestionType.CODING,
    title: "Contains Duplicate",
    slug: "contains-duplicate",
    prompt: buildCodingPrompt(
      "Given an integer array nums, return true if any value appears at least twice in the array. Otherwise return false.",
      [
        { input: "nums = [1,2,3,1]", output: "true" },
        { input: "nums = [1,2,3,4]", output: "false" },
      ],
      ["1 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 10,
    topicTags: ["array", "hash-set"],
  },
  {
    type: QuestionType.CODING,
    title: "Binary Search",
    slug: "binary-search",
    prompt: buildCodingPrompt(
      "Given a sorted array of integers nums and an integer target, return the index of target if it exists. Otherwise return -1.",
      [
        { input: "nums = [-1,0,3,5,9,12], target = 9", output: "4" },
        { input: "nums = [-1,0,3,5,9,12], target = 2", output: "-1" },
      ],
      ["1 <= nums.length <= 10^4", "-10^4 <= nums[i], target <= 10^4", "nums is sorted in increasing order"],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["binary-search", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Reverse Linked List",
    slug: "reverse-linked-list",
    prompt: buildCodingPrompt(
      "Given the head of a singly linked list, reverse the list and return the new head.",
      [
        { input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]" },
        { input: "head = [1,2]", output: "[2,1]" },
      ],
      ["0 <= number of nodes <= 5000", "-5000 <= Node.val <= 5000"],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["linked-list"],
  },
  {
    type: QuestionType.CODING,
    title: "Maximum Depth of Binary Tree",
    slug: "maximum-depth-of-binary-tree",
    prompt: buildCodingPrompt(
      "Given the root of a binary tree, return its maximum depth.",
      [
        { input: "root = [3,9,20,null,null,15,7]", output: "3" },
        { input: "root = [1,null,2]", output: "2" },
      ],
      ["0 <= number of nodes <= 10^4", "-100 <= Node.val <= 100"],
      ["Depth is the number of nodes on the longest root-to-leaf path."],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["tree", "dfs", "bfs"],
  },
  {
    type: QuestionType.CODING,
    title: "Product of Array Except Self",
    slug: "product-of-array-except-self",
    prompt: buildCodingPrompt(
      "Given an integer array nums, return an array answer where answer[i] is the product of every value in nums except nums[i].",
      [
        { input: "nums = [1,2,3,4]", output: "[24,12,8,6]" },
        { input: "nums = [-1,1,0,-3,3]", output: "[0,0,9,0,0]" },
      ],
      ["2 <= nums.length <= 10^5", "-30 <= nums[i] <= 30", "Prefix and suffix products fit in a 32-bit integer"],
      ["Do not use division.", "Aim for O(n) time."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["array", "prefix-suffix"],
  },
  {
    type: QuestionType.CODING,
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeating-characters",
    prompt: buildCodingPrompt(
      "Given a string s, return the length of the longest substring that contains no repeated characters.",
      [
        { input: 's = "abcabcbb"', output: "3" },
        { input: 's = "bbbbb"', output: "1" },
        { input: 's = "pwwkew"', output: "3" },
      ],
      ["0 <= s.length <= 5 * 10^4", "s consists of English letters, digits, symbols, and spaces"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["sliding-window", "string", "hash-map"],
  },
  {
    type: QuestionType.CODING,
    title: "Group Anagrams",
    slug: "group-anagrams",
    prompt: buildCodingPrompt(
      "Given an array of strings, group the strings that are anagrams of each other.",
      [
        { input: 'strs = ["eat","tea","tan","ate","nat","bat"]', output: '[["eat","tea","ate"],["tan","nat"],["bat"]]' },
        { input: 'strs = [""]', output: '[[""]]' },
      ],
      ["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100", "strs[i] consists of lowercase English letters"],
      ["The order of groups does not matter."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["hash-map", "string", "sorting"],
  },
  {
    type: QuestionType.CODING,
    title: "3Sum",
    slug: "3sum",
    prompt: buildCodingPrompt(
      "Given an integer array nums, return all unique triplets [nums[i], nums[j], nums[k]] such that i, j, and k are distinct and the three values sum to zero.",
      [
        { input: "nums = [-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]" },
        { input: "nums = [0,1,1]", output: "[]" },
      ],
      ["3 <= nums.length <= 3000", "-10^5 <= nums[i] <= 10^5"],
      ["The order of triplets does not matter.", "Do not include duplicates."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["two-pointers", "sorting", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Container With Most Water",
    slug: "container-with-most-water",
    prompt: buildCodingPrompt(
      "You are given an array height where height[i] is the height of a vertical line. Choose two lines that together with the x-axis form a container with the largest possible area.",
      [
        { input: "height = [1,8,6,2,5,4,8,3,7]", output: "49" },
        { input: "height = [1,1]", output: "1" },
      ],
      ["2 <= height.length <= 10^5", "0 <= height[i] <= 10^4"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["two-pointers", "greedy"],
  },
  {
    type: QuestionType.CODING,
    title: "Search in Rotated Sorted Array",
    slug: "search-in-rotated-sorted-array",
    prompt: buildCodingPrompt(
      "Given a sorted array that has been rotated at an unknown pivot, return the index of target if it exists, or -1 otherwise.",
      [
        { input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4" },
        { input: "nums = [4,5,6,7,0,1,2], target = 3", output: "-1" },
      ],
      ["1 <= nums.length <= 5000", "-10^4 <= nums[i], target <= 10^4", "All values are unique"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["binary-search", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Find Minimum in Rotated Sorted Array",
    slug: "find-minimum-in-rotated-sorted-array",
    prompt: buildCodingPrompt(
      "Given a sorted array that has been rotated between 1 and n times, return the minimum value in the array.",
      [
        { input: "nums = [3,4,5,1,2]", output: "1" },
        { input: "nums = [4,5,6,7,0,1,2]", output: "0" },
      ],
      ["1 <= nums.length <= 5000", "-5000 <= nums[i] <= 5000", "All values are unique"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["binary-search", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Insert Interval",
    slug: "insert-interval",
    prompt: buildCodingPrompt(
      "You are given a sorted list of non-overlapping intervals and a newInterval. Insert newInterval into the list and merge if necessary.",
      [
        { input: "intervals = [[1,3],[6,9]], newInterval = [2,5]", output: "[[1,5],[6,9]]" },
        { input: "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]", output: "[[1,2],[3,10],[12,16]]" },
      ],
      ["0 <= intervals.length <= 10^4", "intervals are sorted by start and do not overlap"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["intervals", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Number of Islands",
    slug: "number-of-islands",
    prompt: buildCodingPrompt(
      "Given a 2D grid of '1's and '0's, return the number of islands. An island is formed by horizontally or vertically adjacent land cells.",
      [
        { input: 'grid = [["1","1","1","1","0"],["1","1","0","1","0"],["1","1","0","0","0"],["0","0","0","0","0"]]', output: "1" },
        { input: 'grid = [["1","1","0","0","0"],["1","1","0","0","0"],["0","0","1","0","0"],["0","0","0","1","1"]]', output: "3" },
      ],
      ["1 <= rows, cols <= 300", "grid[i][j] is either '0' or '1'"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["graph", "dfs", "bfs", "matrix"],
  },
  {
    type: QuestionType.CODING,
    title: "Clone Graph",
    slug: "clone-graph",
    prompt: buildCodingPrompt(
      "Given a reference to a node in a connected undirected graph, return a deep copy of the graph.",
      [
        { input: "adjacency = [[2,4],[1,3],[2,4],[1,3]]", output: "A new graph with the same adjacency structure" },
        { input: "adjacency = [[]]", output: "A new single-node graph" },
      ],
      ["The graph has between 0 and 100 nodes", "1 <= Node.val <= 100"],
      ["Allocate new nodes. Do not reuse nodes from the input graph."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["graph", "dfs", "bfs", "hash-map"],
  },
  {
    type: QuestionType.CODING,
    title: "Course Schedule",
    slug: "course-schedule",
    prompt: buildCodingPrompt(
      "There are numCourses labeled from 0 to numCourses - 1. Given prerequisite pairs [a, b] meaning you must take course b before course a, return true if it is possible to finish all courses.",
      [
        { input: "numCourses = 2, prerequisites = [[1,0]]", output: "true" },
        { input: "numCourses = 2, prerequisites = [[1,0],[0,1]]", output: "false" },
      ],
      ["1 <= numCourses <= 2000", "0 <= prerequisites.length <= 5000"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["graph", "topological-sort", "dfs"],
  },
  {
    type: QuestionType.CODING,
    title: "Kth Largest Element in an Array",
    slug: "kth-largest-element-in-an-array",
    prompt: buildCodingPrompt(
      "Given an integer array nums and an integer k, return the kth largest value in the array.",
      [
        { input: "nums = [3,2,1,5,6,4], k = 2", output: "5" },
        { input: "nums = [3,2,3,1,2,4,5,5,6], k = 4", output: "4" },
      ],
      ["1 <= k <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
      ["This is the kth largest in sorted order, not the kth distinct value."],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["heap", "quickselect", "array"],
  },
  {
    type: QuestionType.CODING,
    title: "Meeting Rooms II",
    slug: "meeting-rooms-ii",
    prompt: buildCodingPrompt(
      "Given an array of meeting time intervals, return the minimum number of conference rooms required.",
      [
        { input: "intervals = [[0,30],[5,10],[15,20]]", output: "2" },
        { input: "intervals = [[7,10],[2,4]]", output: "1" },
      ],
      ["1 <= intervals.length <= 10^4", "0 <= start_i < end_i <= 10^6"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["intervals", "heap", "sorting"],
  },
  {
    type: QuestionType.CODING,
    title: "Linked List Cycle",
    slug: "linked-list-cycle",
    prompt: buildCodingPrompt(
      "Given the head of a linked list, return true if the list contains a cycle, otherwise return false.",
      [
        { input: "head = [3,2,0,-4], pos = 1", output: "true" },
        { input: "head = [1], pos = -1", output: "false" },
      ],
      ["0 <= number of nodes <= 10^4", "-10^5 <= Node.val <= 10^5"],
      ["pos indicates the index the tail points to. It is not given directly to your function."],
    ),
    difficulty: Difficulty.EASY,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["linked-list", "two-pointers"],
  },
  {
    type: QuestionType.CODING,
    title: "Remove Nth Node From End of List",
    slug: "remove-nth-node-from-end-of-list",
    prompt: buildCodingPrompt(
      "Given the head of a linked list, remove the nth node from the end and return the updated head.",
      [
        { input: "head = [1,2,3,4,5], n = 2", output: "[1,2,3,5]" },
        { input: "head = [1], n = 1", output: "[]" },
      ],
      ["1 <= number of nodes <= 30", "1 <= n <= size of list"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["linked-list", "two-pointers"],
  },
  {
    type: QuestionType.CODING,
    title: "LRU Cache",
    slug: "lru-cache",
    prompt: buildCodingPrompt(
      "Design a data structure that supports get(key) and put(key, value) for an LRU cache with fixed capacity. Both operations should run in O(1) average time.",
      [
        { input: "capacity = 2, operations = [put(1,1), put(2,2), get(1), put(3,3), get(2)]", output: "[null, null, 1, null, -1]" },
      ],
      ["1 <= capacity <= 3000", "0 <= key, value <= 10^4", "At most 2 * 10^5 operations"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 35,
    topicTags: ["design", "hash-map", "linked-list"],
  },
  {
    type: QuestionType.CODING,
    title: "Binary Tree Level Order Traversal",
    slug: "binary-tree-level-order-traversal",
    prompt: buildCodingPrompt(
      "Given the root of a binary tree, return the values level by level from top to bottom.",
      [
        { input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]" },
        { input: "root = [1]", output: "[[1]]" },
      ],
      ["0 <= number of nodes <= 2000", "-1000 <= Node.val <= 1000"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["tree", "bfs", "queue"],
  },
  {
    type: QuestionType.CODING,
    title: "Validate Binary Search Tree",
    slug: "validate-binary-search-tree",
    prompt: buildCodingPrompt(
      "Given the root of a binary tree, return true if it is a valid binary search tree, otherwise return false.",
      [
        { input: "root = [2,1,3]", output: "true" },
        { input: "root = [5,1,4,null,null,3,6]", output: "false" },
      ],
      ["1 <= number of nodes <= 10^4", "-2^31 <= Node.val <= 2^31 - 1"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["tree", "dfs", "bst"],
  },
  {
    type: QuestionType.CODING,
    title: "Lowest Common Ancestor of a Binary Search Tree",
    slug: "lowest-common-ancestor-of-a-binary-search-tree",
    prompt: buildCodingPrompt(
      "Given the root of a binary search tree and two nodes p and q, return their lowest common ancestor.",
      [
        { input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", output: "6" },
        { input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4", output: "2" },
      ],
      ["2 <= number of nodes <= 10^5", "-10^9 <= Node.val <= 10^9", "p and q both exist in the tree"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["tree", "bst"],
  },
  {
    type: QuestionType.CODING,
    title: "Word Break",
    slug: "word-break",
    prompt: buildCodingPrompt(
      "Given a string s and a dictionary of words wordDict, return true if s can be segmented into a sequence of one or more dictionary words.",
      [
        { input: 's = "leetcode", wordDict = ["leet","code"]', output: "true" },
        { input: 's = "catsandog", wordDict = ["cats","dog","sand","and","cat"]', output: "false" },
      ],
      ["1 <= s.length <= 300", "1 <= wordDict.length <= 1000", "1 <= wordDict[i].length <= 20"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["dp", "string", "hash-set"],
  },
  {
    type: QuestionType.CODING,
    title: "Coin Change",
    slug: "coin-change",
    prompt: buildCodingPrompt(
      "Given a list of coin denominations and a target amount, return the fewest number of coins needed to make the amount. Return -1 if it cannot be formed.",
      [
        { input: "coins = [1,2,5], amount = 11", output: "3" },
        { input: "coins = [2], amount = 3", output: "-1" },
      ],
      ["1 <= coins.length <= 12", "1 <= coins[i] <= 2^31 - 1", "0 <= amount <= 10^4"],
    ),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["dp"],
  },
];

type QuickQuestionSeed = {
  title: string;
  slug: string;
  description: string;
  examples: Example[];
  constraints: string[];
  notes?: string[];
  difficulty: Difficulty;
  levelTarget: TargetLevel;
  estimatedMinutes: number;
  topicTags: string[];
};

function fromSeed(seed: QuickQuestionSeed): QuestionBankEntry {
  return {
    type: QuestionType.CODING,
    title: seed.title,
    slug: seed.slug,
    prompt: buildCodingPrompt(seed.description, seed.examples, seed.constraints, seed.notes),
    difficulty: seed.difficulty,
    companyStyle: GENERIC,
    levelTarget: seed.levelTarget,
    estimatedMinutes: seed.estimatedMinutes,
    topicTags: seed.topicTags,
  };
}

type SystemDesignSeed = {
  title: string;
  slug: string;
  scenario: string;
  scope: string[];
  focus: string[];
  estimatedMinutes: number;
  topicTags: string[];
};

function buildSystemDesignPrompt(seed: SystemDesignSeed) {
  return [
    seed.scenario,
    "",
    "Scope:",
    ...seed.scope.map((item) => `- ${item}`),
    "",
    "What to cover in the interview:",
    "- Functional requirements and non-functional goals (latency, availability, reliability, cost).",
    "- Core APIs and data model boundaries.",
    "- High-level architecture and critical read/write paths.",
    ...seed.focus.map((item) => `- ${item}`),
    "- Capacity and scaling assumptions when traffic/throughput concerns are active.",
    "- SPOF, bottlenecks, and mitigation tradeoffs.",
  ].join("\n");
}

function fromSystemDesignSeed(seed: SystemDesignSeed): QuestionBankEntry {
  return {
    type: QuestionType.SYSTEM_DESIGN,
    title: seed.title,
    slug: seed.slug,
    prompt: buildSystemDesignPrompt(seed),
    difficulty: Difficulty.MEDIUM,
    companyStyle: GENERIC,
    levelTarget: null,
    estimatedMinutes: seed.estimatedMinutes,
    topicTags: Array.from(new Set(["system-design", ...seed.topicTags])),
  };
}

const EXTRA_QUESTION_SEEDS: QuickQuestionSeed[] = [
  {
    title: "Maximum Subarray",
    slug: "maximum-subarray",
    description: "Given an integer array nums, return the maximum sum of any non-empty contiguous subarray.",
    examples: [
      { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6" },
      { input: "nums = [1]", output: "1" },
    ],
    constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["array", "dp", "kadane"],
  },
  {
    title: "Climbing Stairs",
    slug: "climbing-stairs",
    description: "You can climb either 1 or 2 steps. Return how many distinct ways there are to reach step n.",
    examples: [
      { input: "n = 2", output: "2" },
      { input: "n = 5", output: "8" },
    ],
    constraints: ["1 <= n <= 45"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["dp", "fibonacci"],
  },
  {
    title: "House Robber",
    slug: "house-robber",
    description: "Given money in houses along a street, return max amount without robbing adjacent houses.",
    examples: [
      { input: "nums = [1,2,3,1]", output: "4" },
      { input: "nums = [2,7,9,3,1]", output: "12" },
    ],
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 400"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["dp", "array"],
  },
  {
    title: "House Robber II",
    slug: "house-robber-ii",
    description: "Houses are arranged in a circle. Return max amount you can rob without robbing adjacent houses.",
    examples: [
      { input: "nums = [2,3,2]", output: "3" },
      { input: "nums = [1,2,3,1]", output: "4" },
    ],
    constraints: ["1 <= nums.length <= 100", "0 <= nums[i] <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["dp", "array"],
  },
  {
    title: "Jump Game",
    slug: "jump-game",
    description: "Given nums where nums[i] is max jump length from i, return true if you can reach the last index.",
    examples: [
      { input: "nums = [2,3,1,1,4]", output: "true" },
      { input: "nums = [3,2,1,0,4]", output: "false" },
    ],
    constraints: ["1 <= nums.length <= 10^4", "0 <= nums[i] <= 10^5"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["greedy", "array"],
  },
  {
    title: "Jump Game II",
    slug: "jump-game-ii",
    description: "Given nums where nums[i] is max jump length from i, return minimum jumps to reach the last index.",
    examples: [
      { input: "nums = [2,3,1,1,4]", output: "2" },
      { input: "nums = [2,3,0,1,4]", output: "2" },
    ],
    constraints: ["1 <= nums.length <= 10^4", "0 <= nums[i] <= 1000", "The last index is reachable"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["greedy", "array"],
  },
  {
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    description: "Given string s, return the longest palindromic substring.",
    examples: [
      { input: 's = "babad"', output: '"bab" (or "aba")' },
      { input: 's = "cbbd"', output: '"bb"' },
    ],
    constraints: ["1 <= s.length <= 1000", "s consists of letters and digits"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["string", "two-pointers", "dp"],
  },
  {
    title: "Palindromic Substrings",
    slug: "palindromic-substrings",
    description: "Given string s, return the number of palindromic substrings in s.",
    examples: [
      { input: 's = "abc"', output: "3" },
      { input: 's = "aaa"', output: "6" },
    ],
    constraints: ["1 <= s.length <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["string", "two-pointers", "dp"],
  },
  {
    title: "Longest Increasing Subsequence",
    slug: "longest-increasing-subsequence",
    description: "Given integer array nums, return the length of the longest strictly increasing subsequence.",
    examples: [
      { input: "nums = [10,9,2,5,3,7,101,18]", output: "4" },
      { input: "nums = [7,7,7,7,7]", output: "1" },
    ],
    constraints: ["1 <= nums.length <= 2500", "-10^4 <= nums[i] <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["dp", "binary-search", "array"],
  },
  {
    title: "Decode Ways",
    slug: "decode-ways",
    description: "A message uses A->1 to Z->26. Return number of valid decodings for string s.",
    examples: [
      { input: 's = "12"', output: "2" },
      { input: 's = "06"', output: "0" },
    ],
    constraints: ["1 <= s.length <= 100", "s contains only digits"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["dp", "string"],
  },
  {
    title: "Combination Sum",
    slug: "combination-sum",
    description: "Given distinct candidates and target, return all unique combinations summing to target. A number can be reused.",
    examples: [
      { input: "candidates = [2,3,6,7], target = 7", output: "[[2,2,3],[7]]" },
      { input: "candidates = [2,3,5], target = 8", output: "[[2,2,2,2],[2,3,3],[3,5]]" },
    ],
    constraints: ["1 <= candidates.length <= 30", "2 <= candidates[i] <= 40", "1 <= target <= 40"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["backtracking", "dfs", "array"],
  },
  {
    title: "Combination Sum II",
    slug: "combination-sum-ii",
    description: "Given candidates (can contain duplicates) and target, return unique combinations summing to target where each number is used once.",
    examples: [
      { input: "candidates = [10,1,2,7,6,1,5], target = 8", output: "[[1,1,6],[1,2,5],[1,7],[2,6]]" },
      { input: "candidates = [2,5,2,1,2], target = 5", output: "[[1,2,2],[5]]" },
    ],
    constraints: ["1 <= candidates.length <= 100", "1 <= candidates[i] <= 50", "1 <= target <= 30"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["backtracking", "sorting", "array"],
  },
  {
    title: "Permutations",
    slug: "permutations",
    description: "Given an array of distinct integers nums, return all possible permutations.",
    examples: [
      { input: "nums = [1,2,3]", output: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]" },
      { input: "nums = [0,1]", output: "[[0,1],[1,0]]" },
    ],
    constraints: ["1 <= nums.length <= 6", "-10 <= nums[i] <= 10"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["backtracking", "array"],
  },
  {
    title: "Subsets",
    slug: "subsets",
    description: "Given an integer array nums of unique elements, return all possible subsets.",
    examples: [
      { input: "nums = [1,2,3]", output: "[[],[1],[2],[3],[1,2],[1,3],[2,3],[1,2,3]]" },
      { input: "nums = [0]", output: "[[],[0]]" },
    ],
    constraints: ["1 <= nums.length <= 10", "-10 <= nums[i] <= 10"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["backtracking", "array"],
  },
  {
    title: "Generate Parentheses",
    slug: "generate-parentheses",
    description: "Given n pairs of parentheses, return all combinations of well-formed parentheses.",
    examples: [
      { input: "n = 3", output: '["((()))","(()())","(())()","()(())","()()()"]' },
      { input: "n = 1", output: '["()"]' },
    ],
    constraints: ["1 <= n <= 8"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["backtracking", "string"],
  },
  {
    title: "Daily Temperatures",
    slug: "daily-temperatures",
    description: "Given daily temperatures, return wait days until warmer temperature for each day.",
    examples: [
      { input: "temperatures = [73,74,75,71,69,72,76,73]", output: "[1,1,4,2,1,1,0,0]" },
      { input: "temperatures = [30,40,50,60]", output: "[1,1,1,0]" },
    ],
    constraints: ["1 <= temperatures.length <= 10^5", "30 <= temperatures[i] <= 100"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["stack", "monotonic-stack", "array"],
  },
  {
    title: "Min Stack",
    slug: "min-stack",
    description: "Design a stack supporting push, pop, top, and getMin in O(1) time.",
    examples: [
      { input: "operations = [push(-2), push(0), push(-3), getMin(), pop(), top(), getMin()]", output: "[null,null,null,-3,null,0,-2]" },
    ],
    constraints: ["At most 3 * 10^4 operations", "Methods should run in O(1) time"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["design", "stack"],
  },
  {
    title: "Evaluate Reverse Polish Notation",
    slug: "evaluate-reverse-polish-notation",
    description: "Given tokens in Reverse Polish Notation, evaluate and return integer result.",
    examples: [
      { input: 'tokens = ["2","1","+","3","*"]', output: "9" },
      { input: 'tokens = ["4","13","5","/","+"]', output: "6" },
    ],
    constraints: ["1 <= tokens.length <= 10^4", "tokens are integers or operators +,-,*,/"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["stack", "math"],
  },
  {
    title: "K Closest Points to Origin",
    slug: "k-closest-points-to-origin",
    description: "Given points and integer k, return k points closest to origin.",
    examples: [
      { input: "points = [[1,3],[-2,2]], k = 1", output: "[[-2,2]]" },
      { input: "points = [[3,3],[5,-1],[-2,4]], k = 2", output: "[[3,3],[-2,4]]" },
    ],
    constraints: ["1 <= k <= points.length <= 10^4", "-10^4 <= x_i, y_i <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["heap", "quickselect", "geometry"],
  },
  {
    title: "Task Scheduler",
    slug: "task-scheduler",
    description: "Given tasks as capital letters and cooldown n, return minimum intervals needed to finish all tasks.",
    examples: [
      { input: 'tasks = ["A","A","A","B","B","B"], n = 2', output: "8" },
      { input: 'tasks = ["A","C","A","B","D","B"], n = 1', output: "6" },
    ],
    constraints: ["1 <= tasks.length <= 10^4", "0 <= n <= 100"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["greedy", "counting", "heap"],
  },
  {
    title: "Set Matrix Zeroes",
    slug: "set-matrix-zeroes",
    description: "If an element in m x n matrix is 0, set its entire row and column to 0 in-place.",
    examples: [
      { input: "matrix = [[1,1,1],[1,0,1],[1,1,1]]", output: "[[1,0,1],[0,0,0],[1,0,1]]" },
      { input: "matrix = [[0,1],[1,1]]", output: "[[0,0],[0,1]]" },
    ],
    constraints: ["1 <= m, n <= 200", "-2^31 <= matrix[i][j] <= 2^31 - 1"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["matrix", "array"],
  },
  {
    title: "Spiral Matrix",
    slug: "spiral-matrix",
    description: "Given an m x n matrix, return all elements in spiral order.",
    examples: [
      { input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[1,2,3,6,9,8,7,4,5]" },
      { input: "matrix = [[1,2],[3,4]]", output: "[1,2,4,3]" },
    ],
    constraints: ["1 <= m, n <= 10", "-100 <= matrix[i][j] <= 100"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["matrix", "simulation"],
  },
  {
    title: "Rotate Image",
    slug: "rotate-image",
    description: "Given an n x n matrix, rotate the image by 90 degrees clockwise in-place.",
    examples: [
      { input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[[7,4,1],[8,5,2],[9,6,3]]" },
      { input: "matrix = [[1,2],[3,4]]", output: "[[3,1],[4,2]]" },
    ],
    constraints: ["n == matrix.length == matrix[i].length", "1 <= n <= 20"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["matrix", "array"],
  },
  {
    title: "Search a 2D Matrix",
    slug: "search-a-2d-matrix",
    description: "Rows are sorted and each row's first element is greater than previous row's last. Return whether target exists.",
    examples: [
      { input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3", output: "true" },
      { input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13", output: "false" },
    ],
    constraints: ["1 <= m, n <= 100", "-10^4 <= matrix[i][j], target <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["binary-search", "matrix"],
  },
  {
    title: "Pacific Atlantic Water Flow",
    slug: "pacific-atlantic-water-flow",
    description: "Given a matrix of heights, return coordinates where water can flow to both Pacific and Atlantic oceans.",
    examples: [
      { input: "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", output: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[4,0]]" },
    ],
    constraints: ["1 <= m, n <= 200", "0 <= heights[r][c] <= 10^5"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["graph", "dfs", "matrix"],
  },
  {
    title: "Surrounded Regions",
    slug: "surrounded-regions",
    description: "Capture all regions surrounded by X in a board by flipping surrounded O to X.",
    examples: [
      { input: 'board = [["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]', output: '[["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]' },
    ],
    constraints: ["1 <= m, n <= 200", "board[i][j] is X or O"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["graph", "dfs", "matrix"],
  },
  {
    title: "Rotting Oranges",
    slug: "rotting-oranges",
    description: "Return minimum minutes until no fresh orange remains, or -1 if impossible.",
    examples: [
      { input: "grid = [[2,1,1],[1,1,0],[0,1,1]]", output: "4" },
      { input: "grid = [[2,1,1],[0,1,1],[1,0,1]]", output: "-1" },
    ],
    constraints: ["1 <= m, n <= 10", "grid values are 0, 1, or 2"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["bfs", "queue", "matrix"],
  },
  {
    title: "Binary Tree Right Side View",
    slug: "binary-tree-right-side-view",
    description: "Return the values of nodes visible from the right side of a binary tree.",
    examples: [
      { input: "root = [1,2,3,null,5,null,4]", output: "[1,3,4]" },
      { input: "root = [1,null,3]", output: "[1,3]" },
    ],
    constraints: ["0 <= number of nodes <= 100", "-100 <= Node.val <= 100"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["tree", "bfs", "dfs"],
  },
  {
    title: "Kth Smallest Element in a BST",
    slug: "kth-smallest-element-in-a-bst",
    description: "Given a BST root and integer k, return the kth smallest value in the tree.",
    examples: [
      { input: "root = [3,1,4,null,2], k = 1", output: "1" },
      { input: "root = [5,3,6,2,4,null,null,1], k = 3", output: "3" },
    ],
    constraints: ["1 <= k <= number of nodes <= 10^4", "0 <= Node.val <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["tree", "bst", "inorder"],
  },
  {
    title: "Serialize and Deserialize Binary Tree",
    slug: "serialize-and-deserialize-binary-tree",
    description: "Design serialize and deserialize methods for a binary tree using any deterministic format.",
    examples: [{ input: "root = [1,2,3,null,null,4,5]", output: "deserialize(serialize(root)) reconstructs an equivalent tree" }],
    constraints: ["0 <= number of nodes <= 10^4", "-1000 <= Node.val <= 1000"],
    notes: ["serialize and deserialize must be inverse operations"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["tree", "design", "bfs", "dfs"],
  },
  {
    title: "Construct Binary Tree from Preorder and Inorder Traversal",
    slug: "construct-binary-tree-from-preorder-and-inorder-traversal",
    description: "Given preorder and inorder traversal arrays with unique values, construct the binary tree.",
    examples: [{ input: "preorder = [3,9,20,15,7], inorder = [9,3,15,20,7]", output: "root = [3,9,20,null,null,15,7]" }],
    constraints: ["1 <= preorder.length == inorder.length <= 3000", "Values are unique"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["tree", "dfs", "hash-map"],
  },
  {
    title: "Path Sum II",
    slug: "path-sum-ii",
    description: "Return all root-to-leaf paths where the sum of node values equals targetSum.",
    examples: [{ input: "root = [5,4,8,11,null,13,4,7,2,null,null,5,1], targetSum = 22", output: "[[5,4,11,2],[5,8,4,5]]" }],
    constraints: ["0 <= number of nodes <= 5000", "-1000 <= Node.val <= 1000", "-1000 <= targetSum <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["tree", "dfs", "backtracking"],
  },
  {
    title: "Diameter of Binary Tree",
    slug: "diameter-of-binary-tree",
    description: "Return the diameter of a binary tree (longest path between any two nodes measured in edges).",
    examples: [
      { input: "root = [1,2,3,4,5]", output: "3" },
      { input: "root = [1,2]", output: "1" },
    ],
    constraints: ["1 <= number of nodes <= 10^4", "-100 <= Node.val <= 100"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 20,
    topicTags: ["tree", "dfs"],
  },
  {
    title: "Same Tree",
    slug: "same-tree",
    description: "Return true if two binary trees are structurally identical and have equal node values.",
    examples: [
      { input: "p = [1,2,3], q = [1,2,3]", output: "true" },
      { input: "p = [1,2], q = [1,null,2]", output: "false" },
    ],
    constraints: ["0 <= number of nodes <= 100", "-10^4 <= Node.val <= 10^4"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["tree", "dfs", "bfs"],
  },
  {
    title: "Subtree of Another Tree",
    slug: "subtree-of-another-tree",
    description: "Return true if subRoot is a subtree of root.",
    examples: [
      { input: "root = [3,4,5,1,2], subRoot = [4,1,2]", output: "true" },
      { input: "root = [3,4,5,1,2,null,null,null,null,0], subRoot = [4,1,2]", output: "false" },
    ],
    constraints: ["1 <= nodes in root <= 2000", "1 <= nodes in subRoot <= 1000"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["tree", "dfs"],
  },
  {
    title: "Minimum Window Substring",
    slug: "minimum-window-substring",
    description: "Return the smallest substring of s that contains all characters of t. Return empty string if impossible.",
    examples: [
      { input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' },
      { input: 's = "a", t = "aa"', output: '""' },
    ],
    constraints: ["1 <= s.length, t.length <= 10^5", "s and t contain English letters"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["sliding-window", "string", "hash-map"],
  },
  {
    title: "Find All Anagrams in a String",
    slug: "find-all-anagrams-in-a-string",
    description: "Return all start indices of p's anagrams in s.",
    examples: [
      { input: 's = "cbaebabacd", p = "abc"', output: "[0,6]" },
      { input: 's = "abab", p = "ab"', output: "[0,1,2]" },
    ],
    constraints: ["1 <= s.length, p.length <= 3 * 10^4", "s and p consist of lowercase letters"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["sliding-window", "string", "hash-map"],
  },
  {
    title: "Valid Anagram",
    slug: "valid-anagram",
    description: "Return true if t is an anagram of s.",
    examples: [
      { input: 's = "anagram", t = "nagaram"', output: "true" },
      { input: 's = "rat", t = "car"', output: "false" },
    ],
    constraints: ["1 <= s.length, t.length <= 5 * 10^4"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 10,
    topicTags: ["hash-map", "string", "sorting"],
  },
  {
    title: "Sort Colors",
    slug: "sort-colors",
    description: "Sort an array of 0,1,2 in-place so equal values are adjacent in order 0,1,2.",
    examples: [
      { input: "nums = [2,0,2,1,1,0]", output: "[0,0,1,1,2,2]" },
      { input: "nums = [2,0,1]", output: "[0,1,2]" },
    ],
    constraints: ["1 <= nums.length <= 300", "nums[i] is 0, 1, or 2"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["two-pointers", "array", "sorting"],
  },
  {
    title: "Find Peak Element",
    slug: "find-peak-element",
    description: "Return an index of any peak element in nums.",
    examples: [
      { input: "nums = [1,2,3,1]", output: "2" },
      { input: "nums = [1,2,1,3,5,6,4]", output: "1 or 5" },
    ],
    constraints: ["1 <= nums.length <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["binary-search", "array"],
  },
  {
    title: "Find First and Last Position of Element in Sorted Array",
    slug: "find-first-and-last-position-of-element-in-sorted-array",
    description: "In sorted nums, return start and end indices of target, or [-1,-1] if absent.",
    examples: [
      { input: "nums = [5,7,7,8,8,10], target = 8", output: "[3,4]" },
      { input: "nums = [5,7,7,8,8,10], target = 6", output: "[-1,-1]" },
    ],
    constraints: ["0 <= nums.length <= 10^5", "-10^9 <= nums[i], target <= 10^9"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 25,
    topicTags: ["binary-search", "array"],
  },
  {
    title: "Merge k Sorted Lists",
    slug: "merge-k-sorted-lists",
    description: "Merge an array of k sorted linked lists into one sorted linked list.",
    examples: [
      { input: "lists = [[1,4,5],[1,3,4],[2,6]]", output: "[1,1,2,3,4,4,5,6]" },
      { input: "lists = []", output: "[]" },
    ],
    constraints: ["0 <= k <= 10^4", "0 <= total nodes <= 10^4", "-10^4 <= Node.val <= 10^4"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["linked-list", "heap", "divide-and-conquer"],
  },
  {
    title: "Median of Two Sorted Arrays",
    slug: "median-of-two-sorted-arrays",
    description: "Given two sorted arrays nums1 and nums2, return median in O(log(m+n)) time.",
    examples: [
      { input: "nums1 = [1,3], nums2 = [2]", output: "2.0" },
      { input: "nums1 = [1,2], nums2 = [3,4]", output: "2.5" },
    ],
    constraints: ["0 <= m, n <= 1000", "1 <= m + n <= 2000"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 45,
    topicTags: ["binary-search", "array"],
  },
  {
    title: "Trapping Rain Water",
    slug: "trapping-rain-water",
    description: "Given elevation map bars, return total trapped rainwater.",
    examples: [
      { input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" },
      { input: "height = [4,2,0,3,2,5]", output: "9" },
    ],
    constraints: ["1 <= height.length <= 2 * 10^4", "0 <= height[i] <= 10^5"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 35,
    topicTags: ["two-pointers", "stack", "array"],
  },
  {
    title: "Sliding Window Maximum",
    slug: "sliding-window-maximum",
    description: "Given nums and window size k, return maximum value in each sliding window.",
    examples: [
      { input: "nums = [1,3,-1,-3,5,3,6,7], k = 3", output: "[3,3,5,5,6,7]" },
      { input: "nums = [1], k = 1", output: "[1]" },
    ],
    constraints: ["1 <= nums.length <= 10^5", "1 <= k <= nums.length"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["deque", "sliding-window", "array"],
  },
  {
    title: "Word Ladder",
    slug: "word-ladder",
    description: "Return shortest transformation sequence length from beginWord to endWord with one-letter changes and intermediate words in dictionary.",
    examples: [
      { input: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log","cog"]', output: "5" },
      { input: 'beginWord = "hit", endWord = "cog", wordList = ["hot","dot","dog","lot","log"]', output: "0" },
    ],
    constraints: ["1 <= wordList.length <= 5000", "All words have same length"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["graph", "bfs", "string"],
  },
  {
    title: "Network Delay Time",
    slug: "network-delay-time",
    description: "Given directed weighted edges and source k, return time needed for all nodes to receive signal, or -1.",
    examples: [
      { input: "times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2", output: "2" },
      { input: "times = [[1,2,1]], n = 2, k = 2", output: "-1" },
    ],
    constraints: ["1 <= n <= 100", "1 <= times.length <= 6000", "0 <= w <= 100"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["graph", "dijkstra", "heap"],
  },
  {
    title: "Accounts Merge",
    slug: "accounts-merge",
    description: "Merge account entries that share common emails and return merged accounts with sorted emails.",
    examples: [
      { input: 'accounts = [["John","johnsmith@mail.com","john_newyork@mail.com"],["John","johnsmith@mail.com","john00@mail.com"],["Mary","mary@mail.com"],["John","johnnybravo@mail.com"]]', output: '[["John","john00@mail.com","john_newyork@mail.com","johnsmith@mail.com"],["Mary","mary@mail.com"],["John","johnnybravo@mail.com"]]' },
    ],
    constraints: ["1 <= accounts.length <= 1000", "Each account contains at least one email"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["union-find", "graph", "hash-map"],
  },
  {
    title: "Implement Trie (Prefix Tree)",
    slug: "implement-trie-prefix-tree",
    description: "Implement a trie with insert(word), search(word), and startsWith(prefix).",
    examples: [{ input: 'ops = [insert("apple"), search("apple"), search("app"), startsWith("app"), insert("app"), search("app")]', output: "[null,true,false,true,null,true]" }],
    constraints: ["1 <= word.length, prefix.length <= 2000", "At most 3 * 10^4 calls"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["trie", "design", "string"],
  },
  {
    title: "Word Search",
    slug: "word-search",
    description: "Return true if word exists in the grid via adjacent moves without reusing a cell.",
    examples: [
      { input: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCCED"', output: "true" },
      { input: 'board = [["A","B","C","E"],["S","F","C","S"],["A","D","E","E"]], word = "ABCB"', output: "false" },
    ],
    constraints: ["1 <= m, n <= 6", "1 <= word.length <= 15"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["backtracking", "dfs", "matrix"],
  },
  {
    title: "Single Number",
    slug: "single-number-extended",
    description: "Given a non-empty array where every element appears twice except one, return the single element.",
    examples: [{ input: "nums = [4,1,2,1,2]", output: "4" }],
    constraints: ["1 <= nums.length <= 3 * 10^4", "-3 * 10^4 <= nums[i] <= 3 * 10^4"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["bit-manipulation", "array"],
  },
  {
    title: "Majority Element",
    slug: "majority-element-extended",
    description: "Return the element that appears more than n/2 times in the array.",
    examples: [{ input: "nums = [2,2,1,1,1,2,2]", output: "2" }],
    constraints: ["1 <= nums.length <= 5 * 10^4", "-10^9 <= nums[i] <= 10^9"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["array", "voting", "greedy"],
  },
  {
    title: "Move Zeroes",
    slug: "move-zeroes-extended",
    description: "Move all zeroes to the end while keeping the relative order of non-zero elements.",
    examples: [{ input: "nums = [0,1,0,3,12]", output: "[1,3,12,0,0]" }],
    constraints: ["1 <= nums.length <= 10^4", "-2^31 <= nums[i] <= 2^31 - 1"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["array", "two-pointers"],
  },
  {
    title: "Find Pivot Index",
    slug: "find-pivot-index-extended",
    description: "Return the leftmost pivot index where left sum equals right sum.",
    examples: [{ input: "nums = [1,7,3,6,5,6]", output: "3" }],
    constraints: ["1 <= nums.length <= 10^4", "-1000 <= nums[i] <= 1000"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["array", "prefix-sum"],
  },
  {
    title: "Subarray Sum Equals K",
    slug: "subarray-sum-equals-k-extended",
    description: "Return the total number of continuous subarrays whose sum equals k.",
    examples: [{ input: "nums = [1,1,1], k = 2", output: "2" }],
    constraints: ["1 <= nums.length <= 2 * 10^4", "-1000 <= nums[i] <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["array", "prefix-sum", "hash-map"],
  },
  {
    title: "Maximum Product Subarray",
    slug: "maximum-product-subarray-extended",
    description: "Return the largest product of a contiguous subarray.",
    examples: [{ input: "nums = [2,3,-2,4]", output: "6" }],
    constraints: ["1 <= nums.length <= 2 * 10^4", "-10 <= nums[i] <= 10"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["array", "dp"],
  },
  {
    title: "Longest Consecutive Sequence",
    slug: "longest-consecutive-sequence-extended",
    description: "Return the length of the longest consecutive sequence in an unsorted array.",
    examples: [{ input: "nums = [100,4,200,1,3,2]", output: "4" }],
    constraints: ["0 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["array", "hash-set"],
  },
  {
    title: "Find Duplicate Number",
    slug: "find-duplicate-number-extended",
    description: "Given n + 1 integers where each integer is in [1, n], return the repeated number.",
    examples: [{ input: "nums = [1,3,4,2,2]", output: "2" }],
    constraints: ["2 <= nums.length <= 10^5", "Exactly one duplicate value exists"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["array", "two-pointers", "cycle-detection"],
  },
  {
    title: "Find the Celebrity",
    slug: "find-the-celebrity-extended",
    description: "Given a knows(a, b) API, find the celebrity among n people if one exists.",
    examples: [{ input: "n = 3, knows matrix = [[0,1,1],[0,0,1],[0,0,0]]", output: "2" }],
    constraints: ["1 <= n <= 500", "Minimize API calls"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["graph", "two-pointers", "elimination"],
  },
  {
    title: "Word Pattern",
    slug: "word-pattern-extended",
    description: "Return true if a pattern string and a sentence follow the same bijection.",
    examples: [{ input: 'pattern = "abba", s = "dog cat cat dog"', output: "true" }],
    constraints: ["1 <= pattern.length <= 300", "1 <= number of words <= 300"],
    difficulty: Difficulty.EASY,
    levelTarget: TargetLevel.NEW_GRAD,
    estimatedMinutes: 15,
    topicTags: ["hash-map", "string"],
  },
  {
    title: "Reorder List",
    slug: "reorder-list-extended",
    description: "Reorder linked list L0→L1→…→Ln into L0→Ln→L1→Ln-1→… in-place.",
    examples: [{ input: "head = [1,2,3,4]", output: "[1,4,2,3]" }],
    constraints: ["1 <= number of nodes <= 5 * 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["linked-list", "two-pointers", "stack"],
  },
  {
    title: "Odd Even Linked List",
    slug: "odd-even-linked-list-extended",
    description: "Group all odd index nodes followed by even index nodes while preserving relative order.",
    examples: [{ input: "head = [1,2,3,4,5]", output: "[1,3,5,2,4]" }],
    constraints: ["0 <= number of nodes <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["linked-list"],
  },
  {
    title: "Binary Tree Zigzag Level Order Traversal",
    slug: "binary-tree-zigzag-level-order-traversal-extended",
    description: "Return the zigzag level order traversal of a binary tree.",
    examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "[[3],[20,9],[15,7]]" }],
    constraints: ["0 <= number of nodes <= 2000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["tree", "bfs", "queue"],
  },
  {
    title: "All Nodes Distance K in Binary Tree",
    slug: "all-nodes-distance-k-in-binary-tree-extended",
    description: "Given target node and integer k, return values of all nodes distance k away.",
    examples: [{ input: "root = [3,5,1,6,2,0,8,null,null,7,4], target = 5, k = 2", output: "[7,4,1]" }],
    constraints: ["1 <= number of nodes <= 500", "0 <= k <= 1000"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["tree", "graph", "bfs"],
  },
  {
    title: "Redundant Connection",
    slug: "redundant-connection-extended",
    description: "Given edges of a graph that started as a tree, return the extra edge that creates a cycle.",
    examples: [{ input: "edges = [[1,2],[1,3],[2,3]]", output: "[2,3]" }],
    constraints: ["3 <= edges.length <= 1000", "Node labels are in [1, n]"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["union-find", "graph"],
  },
  {
    title: "Cheapest Flights Within K Stops",
    slug: "cheapest-flights-within-k-stops-extended",
    description: "Return the cheapest price from src to dst with at most k stops, or -1.",
    examples: [{ input: "n = 4, flights = [[0,1,100],[1,2,100],[2,0,100],[1,3,600],[2,3,200]], src = 0, dst = 3, k = 1", output: "700" }],
    constraints: ["1 <= n <= 100", "0 <= flights.length <= n * (n - 1) / 2"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["graph", "shortest-path", "dp"],
  },
  {
    title: "Alien Dictionary",
    slug: "alien-dictionary-extended",
    description: "Given sorted words in an alien language, return one valid character ordering.",
    examples: [{ input: 'words = ["wrt","wrf","er","ett","rftt"]', output: '"wertf"' }],
    constraints: ["1 <= words.length <= 100", "1 <= words[i].length <= 100"],
    difficulty: Difficulty.HARD,
    levelTarget: TargetLevel.SENIOR,
    estimatedMinutes: 40,
    topicTags: ["graph", "topological-sort", "string"],
  },
  {
    title: "Minimum Cost to Connect Sticks",
    slug: "minimum-cost-to-connect-sticks-extended",
    description: "Connect sticks with minimum total cost where combining x and y costs x + y.",
    examples: [{ input: "sticks = [2,4,3]", output: "14" }],
    constraints: ["1 <= sticks.length <= 10^4", "1 <= sticks[i] <= 10^4"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 20,
    topicTags: ["heap", "greedy"],
  },
  {
    title: "Intervals Between Identical Elements",
    slug: "intervals-between-identical-elements-extended",
    description: "For each index i, compute the sum of distances from i to all other indices with the same value.",
    examples: [{ input: "arr = [2,1,3,1,2,3,3]", output: "[4,2,7,2,4,4,5]" }],
    constraints: ["1 <= arr.length <= 10^5", "1 <= arr[i] <= 10^5"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 35,
    topicTags: ["array", "prefix-sum", "hash-map"],
  },
  {
    title: "Minimum Remove to Make Valid Parentheses",
    slug: "minimum-remove-to-make-valid-parentheses-extended",
    description: "Remove minimum parentheses to make input string valid and return any valid result.",
    examples: [{ input: 's = "lee(t(c)o)de)"', output: '"lee(t(c)o)de"' }],
    constraints: ["1 <= s.length <= 10^5"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE1,
    estimatedMinutes: 25,
    topicTags: ["stack", "string"],
  },
  {
    title: "Basic Calculator II",
    slug: "basic-calculator-ii-extended",
    description: "Evaluate a simple expression string with +, -, *, / and non-negative integers.",
    examples: [{ input: 's = "3+2*2"', output: "7" }],
    constraints: ["1 <= s.length <= 3 * 10^5", "s consists of digits, operators, and spaces"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["stack", "string", "math"],
  },
  {
    title: "Random Pick with Weight",
    slug: "random-pick-with-weight-extended",
    description: "Design pickIndex() so index i is chosen with probability proportional to weight w[i].",
    examples: [{ input: "w = [1,3], pickIndex() called many times", output: "index 1 is returned about 75% of the time" }],
    constraints: ["1 <= w.length <= 10^4", "1 <= w[i] <= 10^5"],
    difficulty: Difficulty.MEDIUM,
    levelTarget: TargetLevel.SDE2,
    estimatedMinutes: 30,
    topicTags: ["binary-search", "prefix-sum", "design"],
  },
];

const SYSTEM_DESIGN_QUESTION_SEEDS: SystemDesignSeed[] = [
  {
    title: "Design Twitter/X Feed",
    slug: "system-design-twitter-feed",
    scenario: "Design a Twitter/X-like social feed service with tweet publishing and timeline fanout.",
    scope: ["Users publish posts and follow other users.", "Users load home timeline with low latency.", "Users can like/repost and view counts."],
    focus: ["Fanout on write vs fanout on read tradeoff.", "Hot user handling and timeline caching strategy."],
    estimatedMinutes: 50,
    topicTags: ["feed", "fanout", "cache"],
  },
  {
    title: "Design Instagram",
    slug: "system-design-instagram",
    scenario: "Design an Instagram-like photo sharing platform.",
    scope: ["Users upload photos/videos.", "Users view personalized feed and stories.", "Users interact via likes/comments."],
    focus: ["Media storage/CDN strategy.", "Feed ranking pipeline boundaries."],
    estimatedMinutes: 50,
    topicTags: ["media", "feed", "cdn"],
  },
  {
    title: "Design WhatsApp",
    slug: "system-design-whatsapp",
    scenario: "Design a WhatsApp-like real-time messaging platform.",
    scope: ["1:1 and group messaging.", "Message delivery/read receipts.", "Online presence and last seen."],
    focus: ["Realtime delivery guarantees and offline sync.", "Ordering, idempotency, and retry model."],
    estimatedMinutes: 50,
    topicTags: ["messaging", "realtime", "consistency"],
  },
  {
    title: "Design Slack",
    slug: "system-design-slack",
    scenario: "Design a Slack-like team chat and channel collaboration system.",
    scope: ["Workspace/channel messaging.", "Search over historical messages.", "File attachments in channels."],
    focus: ["Channel shard model and websocket scaling.", "Search indexing and retention strategy."],
    estimatedMinutes: 50,
    topicTags: ["messaging", "search", "websocket"],
  },
  {
    title: "Design YouTube",
    slug: "system-design-youtube",
    scenario: "Design a YouTube-like video upload and streaming system.",
    scope: ["Video upload and transcoding.", "Playback with adaptive bitrate.", "Metadata, comments, and engagement counters."],
    focus: ["Transcoding pipeline and storage lifecycle.", "Global CDN and cache invalidation strategy."],
    estimatedMinutes: 55,
    topicTags: ["video", "cdn", "pipeline"],
  },
  {
    title: "Design Netflix Streaming",
    slug: "system-design-netflix-streaming",
    scenario: "Design a Netflix-like on-demand video streaming platform.",
    scope: ["Catalog browsing and playback.", "Personalized recommendations integration points.", "Session resume and watch progress."],
    focus: ["Playback latency and startup optimization.", "Regional failover and content delivery resilience."],
    estimatedMinutes: 55,
    topicTags: ["streaming", "cdn", "reliability"],
  },
  {
    title: "Design Uber Ride Matching",
    slug: "system-design-uber-ride-matching",
    scenario: "Design an Uber-like ride matching platform.",
    scope: ["Rider request and driver matching.", "Live trip tracking.", "ETA and pricing estimate."],
    focus: ["Geo-indexing for nearby driver lookup.", "Dispatch fairness vs latency tradeoff."],
    estimatedMinutes: 55,
    topicTags: ["geo", "dispatch", "realtime"],
  },
  {
    title: "Design DoorDash Order Dispatch",
    slug: "system-design-doordash-dispatch",
    scenario: "Design a DoorDash-like food delivery dispatch system.",
    scope: ["Order placement and restaurant acceptance.", "Courier assignment and tracking.", "Order status timeline updates."],
    focus: ["Multi-sided marketplace consistency.", "Dispatch optimization under surge."],
    estimatedMinutes: 55,
    topicTags: ["delivery", "dispatch", "marketplace"],
  },
  {
    title: "Design Google Maps Nearby Search",
    slug: "system-design-google-maps-nearby-search",
    scenario: "Design a nearby places search service like Google Maps.",
    scope: ["Users query nearby places by location and category.", "Return ranked results with metadata.", "Support map viewport updates."],
    focus: ["Geo-hash / S2 indexing choices.", "Ranking freshness vs latency tradeoff."],
    estimatedMinutes: 50,
    topicTags: ["geo", "search", "indexing"],
  },
  {
    title: "Design Waze Traffic Ingestion",
    slug: "system-design-waze-traffic-ingestion",
    scenario: "Design a Waze-like live traffic ingestion and routing signal system.",
    scope: ["Ingest anonymized GPS pings.", "Detect congestion/incidents.", "Serve routing quality signals."],
    focus: ["High-volume stream processing architecture.", "Outlier filtering and stale-data handling."],
    estimatedMinutes: 50,
    topicTags: ["streaming", "geo", "analytics"],
  },
  {
    title: "Design LeetCode Judge",
    slug: "system-design-leetcode-judge",
    scenario: "Design an online coding judge platform like LeetCode.",
    scope: ["Submit code in multiple languages.", "Run against hidden/public test sets.", "Return verdict and runtime stats."],
    focus: ["Sandbox/isolation model.", "Queueing and autoscaling workers."],
    estimatedMinutes: 50,
    topicTags: ["execution", "sandbox", "queue"],
  },
  {
    title: "Design GitHub Notifications",
    slug: "system-design-github-notifications",
    scenario: "Design a GitHub-like notifications system.",
    scope: ["Generate events for repo activities.", "Deliver in-app and email notifications.", "Support per-user notification preferences."],
    focus: ["Event fanout and deduplication.", "Preference filtering pipeline."],
    estimatedMinutes: 45,
    topicTags: ["notifications", "fanout", "preferences"],
  },
  {
    title: "Design Jira Issue Tracker",
    slug: "system-design-jira-issue-tracker",
    scenario: "Design a Jira-like issue tracking system.",
    scope: ["Project/issue CRUD with workflows.", "Comments and activity history.", "Search/filter by project, assignee, status."],
    focus: ["Workflow state machine and audit log.", "Query indexing strategy for boards."],
    estimatedMinutes: 50,
    topicTags: ["workflow", "search", "audit-log"],
  },
  {
    title: "Design Confluence Docs",
    slug: "system-design-confluence-docs",
    scenario: "Design a Confluence-like collaborative document system.",
    scope: ["Rich text document editing.", "Version history and restore.", "Permissioned sharing."],
    focus: ["Consistency model for collaborative edits.", "Revision storage and diff strategy."],
    estimatedMinutes: 50,
    topicTags: ["docs", "collaboration", "versioning"],
  },
  {
    title: "Design Google Docs Collaboration",
    slug: "system-design-google-docs-collab",
    scenario: "Design a Google Docs-like real-time collaborative editor.",
    scope: ["Multiple users edit same doc concurrently.", "Low-latency cursor/presence updates.", "Version recovery and conflict safety."],
    focus: ["OT vs CRDT tradeoff.", "Session state and persistence boundaries."],
    estimatedMinutes: 55,
    topicTags: ["collaboration", "realtime", "consistency"],
  },
  {
    title: "Design Zoom Meeting Service",
    slug: "system-design-zoom-meeting-service",
    scenario: "Design a Zoom-like video meeting system.",
    scope: ["Create/join meeting rooms.", "Audio/video streams for participants.", "Chat and screen sharing metadata."],
    focus: ["SFU/MCU media routing tradeoff.", "Regional routing and failover."],
    estimatedMinutes: 55,
    topicTags: ["realtime", "video", "sfu"],
  },
  {
    title: "Design Gmail Search",
    slug: "system-design-gmail-search",
    scenario: "Design a Gmail-like mailbox search system.",
    scope: ["Ingest incoming/outgoing email.", "Query by sender/subject/body.", "Support labels and filters."],
    focus: ["Indexing pipeline and query latency.", "Consistency between mailbox state and index."],
    estimatedMinutes: 50,
    topicTags: ["search", "indexing", "mail"],
  },
  {
    title: "Design Calendar Booking",
    slug: "system-design-calendar-booking",
    scenario: "Design a calendar scheduling and booking platform.",
    scope: ["Manage events and availability.", "Find meeting slots for participants.", "Send reminders and update attendees."],
    focus: ["Double-booking prevention model.", "Timezone and recurrence handling."],
    estimatedMinutes: 50,
    topicTags: ["calendar", "consistency", "scheduling"],
  },
  {
    title: "Design Stripe Payments Ledger",
    slug: "system-design-stripe-payments-ledger",
    scenario: "Design a Stripe-like payments and ledger service.",
    scope: ["Authorize/capture/refund payment.", "Maintain immutable ledger entries.", "Expose merchant balance and reports."],
    focus: ["Idempotency and exactly-once semantics.", "Reconciliation and auditability."],
    estimatedMinutes: 55,
    topicTags: ["payments", "ledger", "idempotency"],
  },
  {
    title: "Design Fraud Detection Pipeline",
    slug: "system-design-fraud-detection-pipeline",
    scenario: "Design a real-time fraud detection pipeline for transactions.",
    scope: ["Score transactions in near real time.", "Support rule + model signals.", "Generate review actions and feedback loops."],
    focus: ["Online feature retrieval and latency budget.", "False positive vs recall tradeoff."],
    estimatedMinutes: 55,
    topicTags: ["fraud", "streaming", "ml-systems"],
  },
  {
    title: "Design Feature Flag Platform",
    slug: "system-design-feature-flag-platform",
    scenario: "Design a feature flag management and evaluation platform.",
    scope: ["Create/update flags and targeting rules.", "SDK evaluation in client/server paths.", "Audit changes and rollout history."],
    focus: ["Control plane vs data plane separation.", "Consistency and cache invalidation for rules."],
    estimatedMinutes: 45,
    topicTags: ["config", "control-plane", "cache"],
  },
  {
    title: "Design Rate Limiter Service",
    slug: "system-design-rate-limiter-service",
    scenario: "Design a centralized distributed rate limiter service.",
    scope: ["Per-user/per-API quotas.", "Burst handling and backoff responses.", "Observability for throttling decisions."],
    focus: ["Token bucket/leaky bucket/sliding window tradeoffs.", "Hot key mitigation and regional consistency."],
    estimatedMinutes: 45,
    topicTags: ["rate-limiting", "distributed-systems", "cache"],
  },
  {
    title: "Design API Gateway",
    slug: "system-design-api-gateway",
    scenario: "Design an API gateway platform for microservices.",
    scope: ["Authn/authz and request routing.", "Rate limiting and quota enforcement.", "Request/response transformation and logging."],
    focus: ["Gateway plugin architecture.", "Latency overhead and reliability strategy."],
    estimatedMinutes: 45,
    topicTags: ["api-gateway", "auth", "observability"],
  },
  {
    title: "Design Web Crawler",
    slug: "system-design-web-crawler",
    scenario: "Design a scalable web crawler service.",
    scope: ["Discover and schedule URLs.", "Fetch and parse pages.", "Persist crawl metadata and dedupe content."],
    focus: ["Frontier scheduling and politeness constraints.", "Duplicate detection and recrawl strategy."],
    estimatedMinutes: 50,
    topicTags: ["crawler", "queue", "deduplication"],
  },
  {
    title: "Design Search Autocomplete",
    slug: "system-design-search-autocomplete",
    scenario: "Design a search autocomplete service.",
    scope: ["Return top suggestions for typed prefix.", "Personalized vs global suggestions.", "Support typo tolerance."],
    focus: ["Trie/index structure choices.", "Freshness vs latency tradeoff for updates."],
    estimatedMinutes: 45,
    topicTags: ["autocomplete", "trie", "ranking"],
  },
  {
    title: "Design Log Aggregation Platform",
    slug: "system-design-log-aggregation-platform",
    scenario: "Design a centralized log ingestion and query platform.",
    scope: ["Ingest logs from many services.", "Index/query logs with filters.", "Retention and tiered storage policies."],
    focus: ["Write-heavy ingestion pipeline.", "Index granularity and cost controls."],
    estimatedMinutes: 50,
    topicTags: ["logging", "observability", "storage"],
  },
  {
    title: "Design Metrics and Alerting",
    slug: "system-design-metrics-alerting",
    scenario: "Design a metrics collection and alerting system.",
    scope: ["Collect time-series metrics.", "Query dashboards and aggregates.", "Trigger alerts with suppression rules."],
    focus: ["Time-series storage choices.", "Alert evaluation scaling and dedupe."],
    estimatedMinutes: 50,
    topicTags: ["metrics", "alerting", "time-series"],
  },
  {
    title: "Design S3-like Object Storage",
    slug: "system-design-object-storage",
    scenario: "Design an S3-like distributed object storage service.",
    scope: ["Store/retrieve large immutable objects.", "Namespace buckets and keys.", "Lifecycle and replication policies."],
    focus: ["Metadata and chunk placement strategy.", "Durability model and repair workflow."],
    estimatedMinutes: 55,
    topicTags: ["object-storage", "durability", "replication"],
  },
  {
    title: "Design Kafka-like Event Streaming",
    slug: "system-design-kafka-like-streaming",
    scenario: "Design a Kafka-like distributed event streaming platform.",
    scope: ["Publish/subscribe topics with partitions.", "Consumer groups and offsets.", "Retention and replay."],
    focus: ["Partitioning and leader replication model.", "Ordering, throughput, and recovery tradeoffs."],
    estimatedMinutes: 55,
    topicTags: ["streaming", "pub-sub", "replication"],
  },
];

const EXTRA_QUESTION_BANK: QuestionBankEntry[] = EXTRA_QUESTION_SEEDS.map(fromSeed);
const SYSTEM_DESIGN_EXTRA_BANK: QuestionBankEntry[] = SYSTEM_DESIGN_QUESTION_SEEDS.map(fromSystemDesignSeed);

const ALL_BASE_QUESTION_BANK: QuestionBankEntry[] = [
  ...BASE_QUESTION_BANK,
  ...SYSTEM_DESIGN_EXTRA_BANK,
  ...EXTRA_QUESTION_BANK,
];

const COMPANY_VARIANTS = ALL_BASE_QUESTION_BANK.flatMap((entry) => {
  if (entry.type !== QuestionType.CODING) {
    return [];
  }

  return COMPANY_VARIANT_STYLES.map((companyStyle) => buildCompanyVariant(entry, companyStyle));
});

export const QUESTION_BANK: QuestionBankEntry[] = [...ALL_BASE_QUESTION_BANK, ...COMPANY_VARIANTS];

export function getQuestionPromptByTitle(title: string | null | undefined) {
  if (!title) {
    return null;
  }

  return QUESTION_BANK.find((question) => question.title === title)?.prompt ?? null;
}
